# Generated by Django 6.0.4 on 2026-05-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_booking_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8),
            preserve_default=False,
        ),
    ]
