# Generated by Django 6.0.4 on 2026-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_remove_service_icon_service_image_service_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
