# Generated by Django 6.0.5 on 2026-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.CharField(max_length=100, unique=True)),
                ('card_name', models.CharField(max_length=150)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
