# Generated by Django 6.0.5 on 2026-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='contact_work_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
