# Generated by Django 6.0.5 on 2026-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_systemsetting_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='system/'),
        ),
    ]
