# Generated by Django 6.0.5 on 2026-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_customerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
