# Generated by Django 6.0.5 on 2026-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0034_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_online_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_pay_at_hotel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_payment_method',
            field=models.CharField(choices=[('hotel', 'Pay at Hotel'), ('online', 'Online Payment')], default='hotel', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='show_payment_field',
            field=models.BooleanField(default=True),
        ),
    ]
