# Generated by Django 6.0.5 on 2026-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_amenity_remove_roomtype_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/'),
        ),
    ]
