# Generated by Django 6.0.5 on 2026-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0040_alter_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='check_in_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='check_in_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='check_in_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='check_out_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='check_out_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='check_out_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_bed_info',
            field=models.TextField(blank=True),
        ),
    ]
