# Generated by Django 6.0.5 on 2026-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0045_restaurant_breakfast_time_ar_restaurant_category_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nearbyplace',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
