# Generated by Django 6.0.5 on 2026-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0047_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='facility',
            name='image',
        ),
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
