# Generated by Django 6.0.5 on 2026-06-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0048_alter_facility_options_remove_facility_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
