# Generated by Django 6.0.5 on 2026-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0050_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.JSONField(blank=True, default=list)),
                ('cancellation_policy', models.JSONField(blank=True, default=list)),
                ('terms_conditions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
