# Generated by Django 6.0.5 on 2026-08-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0053_booking_booking_status_booking_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
