# Generated by Django 6.0.5 on 2026-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0054_booking_confirmation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reception_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
