# Generated by Django 6.0.5 on 2026-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0055_booking_reception_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
