# Generated by Django 6.0.5 on 2026-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0056_booking_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
