# Generated by Django 6.0.5 on 2026-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0059_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='zaincash_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='zaincash_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='zaincash_token_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
