# Generated by Django 6.0.5 on 2026-09-08 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0061_nearbyplace_latitude_nearbyplace_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
