# Generated by Django 6.0.5 on 2026-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0062_alter_nearbyplace_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyplace',
            name='icon_type',
            field=models.CharField(choices=[('place', 'مكان عام'), ('religious', 'مكان مقدس'), ('airport', 'مطار'), ('restaurant', 'مطعم'), ('cafe', 'مقهى'), ('shopping', 'تسوّق'), ('museum', 'متحف أو معلم ثقافي'), ('park', 'منتزه'), ('hospital', 'مستشفى'), ('transport', 'مواصلات')], default='place', max_length=20),
        ),
    ]
