# Generated by Django 6.0.5 on 2026-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0063_nearbyplace_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='area_m2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Room area (m²)'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bed type'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='view_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Room view'),
        ),
    ]
