# Generated by Django 6.0.4 on 2026-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('deluxe', 'Deluxe'), ('junior suite', 'Junior Suite'), ('executive suite', 'Executive Suite')], default='deluxe', max_length=20),
        ),
    ]
