# Generated by Django 6.0.4 on 2026-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room_capacity_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booking_open', models.BooleanField(default=True)),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('min_nights', models.IntegerField(default=1)),
                ('max_nights', models.IntegerField(default=30)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('deluxe king', 'Deluxe King'), ('deluxe twin', 'Deluxe Twin'), ('junior king', 'Junior King'), ('junior twin', 'Junior Twin'), ('executive suite', 'Executive Suite')], default='deluxe king', max_length=50),
        ),
    ]
