# Generated by Django 6.0.4 on 2026-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_room_price_remove_room_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('ON', 'Available'), ('OFF', 'Closed')], default='ON', max_length=10),
        ),
    ]
