# Generated by Django 6.0.4 on 2026-05-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_remove_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='nearby_places/')),
                ('location', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
