# Generated by Django 6.0.5 on 2026-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_booking_booking_code_booking_review_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
