# Generated by Django 6.0.5 on 2026-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_systemsetting_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='story_description',
            field=models.TextField(blank=True),
        ),
    ]
