# Generated by Django 6.0.5 on 2026-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0031_mealoption_booking_meal_price_booking_meal_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='$', max_length=10)),
            ],
        ),
    ]
