# Generated by Django 6.0.5 on 2026-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0035_systemsetting_allow_online_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
