# Generated by Django 6.0.5 on 2026-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
