# Generated by Django 6.0.5 on 2026-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_roomtype_amenities_roomtype_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='amenities',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(to='hotels.amenity'),
        ),
    ]
