# Generated by Django 6.0.5 on 2026-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0042_usertablesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCloseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_close_booked_room', models.BooleanField(default=False)),
            ],
        ),
    ]
