from . import views
from django.urls import path
from .views import booking_settings,notification_detail,all_bookings,dashboard_stats, delete_booking, delete_room, get_hotels , get_rooms , bookings , available_rooms , booking_detail , register , my_bookings , profile, hotel_detail, room_types, rooms_by_hotel, update_room


urlpatterns = [
    path('hotels/' , get_hotels),
    path('rooms/' , get_rooms),
    path('bookings/' , bookings),
    path('available_rooms/',available_rooms),
    path('bookings/<int:id>/', booking_detail),
    path('register/', register),
    path('my-bookings/', my_bookings),
    path('profile/', profile),
    path('hotels/<int:id>/', hotel_detail),
    path('hotels/<int:hotel_id>/rooms/', rooms_by_hotel),
    path('register/', register),
    path('booking-settings/', booking_settings),
    path('dashboard-stats/', dashboard_stats),
    path('all-bookings/', all_bookings),
    path('rooms/<int:pk>/', views.room_detail),
    path('rooms/<int:pk>/delete/', delete_room),
    path('rooms/<int:pk>/update/', update_room),
    path('bookings/<int:pk>/', delete_booking),
    path('room-types/', room_types),
    path("room-types/<int:pk>/", views.room_type_detail),
    path("profile/", views.profile),
    path('admin/bookings/', views.admin_bookings),
    path('admin/current-bookings/', views.current_bookings),
    path('room-types/<int:pk>/rooms/', views.rooms_by_type),
    path('rooms/bulk-availability/', views.bulk_room_availability),
    path('restaurants/', views.restaurants),
    path('restaurants/<int:pk>/', views.restaurant_detail),
    path('restaurants/<int:pk>/', views.restaurant_detail),
    path('nearby-places/', views.nearby_places),
    path('nearby-places/<int:pk>/', views.nearby_place_detail),
    path('services/', views.services),
    path('services/<int:pk>/', views.service_detail),
    path('galleries/', views.galleries),
    path('galleries/<int:pk>/', views.gallery_detail),
    path('gallery-images/', views.gallery_images),
    path('gallery-images/<int:pk>/', views.gallery_image_detail),
    path('reviews/', views.reviews),
    path('reviews/<int:pk>/', views.review_detail),
    path('submit-review/', views.submit_review),
    path('staff-users/', views.staff_users),
    path('staff-users/<int:pk>/', views.staff_user_detail),
    path('groups/', views.groups),
    path('groups/<int:pk>/', views.group_detail),
    path('permissions/', views.permissions_list),
    path('logs/', views.logs),
    path('contact-settings/', views.contact_settings),
    path('contact-messages/', views.contact_messages),
    path('contact-messages/<int:pk>/', views.contact_message_detail),
    path('notifications/', views.notifications),
    path('notifications/<int:pk>/', views.notification_detail),
    path('dashboard-card-settings/',views.dashboard_card_settings),
    path('dashboard-card-settings/<int:pk>/',views.dashboard_card_setting_detail),
    path("system-settings/", views.system_settings),
    path("admin-profiles/", views.admin_profiles),
    path("admin-profiles/<int:pk>/", views.admin_profile_detail),
    path("customer-records/", views.customer_records),
    path('rooms/<int:room_id>/bookings/',views.room_bookings),
    path('rooms/<int:room_id>/availability/',views.room_availability),
    path("rooms/bulk-off/", views.rooms_bulk_off),
    path("bookings/<int:booking_id>/toggle-read/",views.toggle_booking_read),
    path("admin-meal-options/<int:meal_id>/", views.admin_meal_option_detail),
    path("meal-options/", views.meal_options),
    path("admin-meal-options/", views.admin_meal_options),
    path("meal-options/<int:meal_id>/toggle/",views.toggle_meal_option),
    path("currencies/", views.currencies),
    path("currencies/<int:pk>/", views.currency_detail),
    path("bookings/<int:booking_id>/pay/",views.fake_payment),
]